### ISSUE TITLE
A way to hide world edit logs/progress in chat

### ISSUE THREAD

**Issue by TheDoverKing** [ThroneCraft/issues#129]
**Is your feature request related to a problem? Please describe.**
Currently when executing any world edit command it shows the progress of it in chat from "processing blocks" to "done". This response from the plugin can become an annoyance when doing multiple commands and especially when you're running commands one after the other in quick succession (like using the //brush tool).

**Describe the solution you'd like**
Just want a method of toggling whether or not world edit shows the progress of a command in chat,  such as how /toggle disables global messages. Or disable the logs altogether since they're not needed and spam your chat.

**Describe alternatives you've considered**
None, the only alternative currently is to not use world edit.

**Additional context**
https://imgur.com/dVPFABz
https://imgur.com/chZxL7Q

***Minecraft username:***
TheDoverKing

**Comment by jvdoorn** [comment]
Should be good!
