### ISSUE TITLE
Admin permissions not seeming to function

### ISSUE THREAD

**Issue by MCVDK** [ThroneCraft/issues#13]
**Describe the bug**
Admins do not seem to have access to; get a key, break and unlock any door

**Expected behaviour**
It is expected that admins can get a key, break and unlock any door

**Screenshots**
/key get gives the following;
[https://gyazo.com/cdc57538c930fe5903a5cd54ab02dd48](https://i.gyazo.com/cdc57538c930fe5903a5cd54ab02dd48.png)

Opening / Breaking the door gives the following; 
[https://gyazo.com/fe876181d2f4be06633c5fdc69de6b33](https://gyazo.com/fe876181d2f4be06633c5fdc69de6b33)

/unlock gives the following;
[https://gyazo.com/8e2873fd1f33f7b689e369dcdb8d0ae6](https://gyazo.com/8e2873fd1f33f7b689e369dcdb8d0ae6
)

***Minecraft username:***
MCVDK

**Comment by jvdoorn** [comment]
Mod+ should now have access to this.
