### ISSUE TITLE
City tag in role request

### ISSUE THREAD

**Issue by Brsssh** [ThroneCraft/issues#131]
**Describe the issue**

The option in #RoleRequest to select your city tag has been removed it seems. This tag is important because it is intended to give players access to a channel that contains a link to their city's discord

***Minecraft username:***

Brsssh

***Discord username:***

Brsssh#7297

**Comment by jvdoorn** [comment]
City roles are given automatically based on your groups on the server. If your city roles are not given properly please create a report with the specific city that is not given.
