### ISSUE TITLE
Build Team needs crop trample turned off plzzz

### ISSUE THREAD

**Issue by Bewby** [ThroneCraft/issues#134]
**Is your feature request related to a problem? Please describe.**
We are making beautiful farms but because of their winding path design, I'm sure people will run thru the fields. Plus running thru the fields will be cool anyways cuz they are dope looking.

**Describe the solution you'd like**
We need crop trample turned off. Should be a global worldguard flag. I think a few plugins offer the feature actually. Essentials might too.

**Additional context**
![image](https://user-images.githubusercontent.com/74216336/104398817-1599b080-5515-11eb-892e-45ff30c5bd10.png)

***Minecraft username:***
Bew

**Comment by FInnJp** [comment]
Alright, the region should now have block trampling denied, however, as most builders (and people who can access the region in the first place) are members of it, thus they bypass most of the flags that are set up there, so you guys can still trample them atm. Although, once the city is done and the region is redone without any members, then this effect should come more in play.
