### ISSUE TITLE
Tab color issue for independent cities

### ISSUE THREAD

**Issue by Brsssh** [ThroneCraft/issues#135]
**Describe the bug**

I still believe this to be related to Issue #132, in which the prefixes and colors of people living in independent outpost were broken, however now it seems that while all other related issues with that bug have been fixed, those people's names now appear as white in tab.

**Screenshots**

![2021-01-13_13 10 06](https://user-images.githubusercontent.com/72952343/104501075-dc108600-55a4-11eb-822b-8342af894673.png)

***Minecraft username:***

Brsssh

**Comment by Bilbo821** [comment]
It specifically seems to be happening with the Anurk and Crucible tags, I'm not sure if any other tags are broken though.

**Comment by Brsssh** [comment]
It happens with all outpost tags from what I’ve seen aside from the the light green, it being the glyndale tag officially.
