### ISSUE TITLE
Pet master 

### ISSUE THREAD

**Issue by stalin27** [ThroneCraft/issues#137]
The bug is one pertaining to the PetMaster, the problem occurred when I got my pet out and was running around as I killed mobs for exp to increase the slots in my Pet Sheep’s inventory, when it started levelling up everything went as normal expect when I went to look into the pet itself, all the items just disappeared like it was never there.

Stalin_71192

**Comment by Brsssh** [comment]
I had this issue a while ago but was never able to duplicate it. For now please contact staff to have the items replaced.
