### ISSUE TITLE
MPM update

### ISSUE THREAD

**Issue by BackupPT** [ThroneCraft/issues#138]
**Is your feature request related to a problem? Please describe.**
Mpm is quite buggy right now.
**Describe the solution you'd like**
Maybe there could be an update to the plugin

***Minecraft username:***
Backup__

**Comment by Brsssh** [comment]
Mpm is a clientside mod, not a plugin. There's nothing Devs can do about it sadly, but if you'd like you can report these issues to the developers of the plugin
