### ISSUE TITLE
/unlock doesn't work

### ISSUE THREAD

**Issue by MCVDK** [ThroneCraft/issues#14]
**Describe the bug**
/unlock doesn't cause the door to unlock

**Expected behaviour**
Door unlocks

**Screenshots**
[https://gyazo.com/1b35bf84c60f1ba8d8252f4c9a2e3877](https://gyazo.com/1b35bf84c60f1ba8d8252f4c9a2e3877)

***Minecraft username:***
MCVDK

**Comment by jvdoorn** [comment]
Could you check if this is still an issue? It works for me so if it somehow doesn't work for you then please be more specific regarding the circumstances.

**Comment by jvdoorn** [comment]
Update: it appears that this is only an issue when you try to unlock the top half of the door. Unlocking the bottom half works just fine.

**Comment by jvdoorn** [comment]
This issue should be fixed after the next restart (tomorrow 8a.m. server time).
