### ISSUE TITLE
Player info resetting

### ISSUE THREAD

**Issue by loulou71192** [ThroneCraft/issues#140]
Multiple player's stats keep resetting including race, full stats, etc.
Unlike the previous issue where this occurred and it was more like a "rollback" to recent info (aka of someone recently changed race, got a stat increase, etc), this seems to be occurring randomly and on some player's, occurring daily.

**Comment by jvdoorn** [comment]
Can you provide us with a date and time of when those users logged in?

**Comment by loulou71192** [comment]
Aurelian_Kilthus: 13:30 CET
ElderUndyne: 12:20 CET
Vladone907: 13:00 CET

All estimates but log on times today when they realised it happened again

**Comment by BackupPT** [comment]
Backup__ 12:00 CET It happens every day I log in. Nickname and stats reset.

**Comment by jvdoorn** [comment]
This issue should be fixed. Reopen it in case the problems persist.
