### ISSUE TITLE
Resetting stats

### ISSUE THREAD

**Issue by ChaoKeeper** [ThroneCraft/issues#144]
So every week or so, my IC stats, race, and name get reset (it happened yesterday too). I’m not sure why it is doing this but it has happened for at least a few weeks now.

***Minecraft username:***

ChaoKeeper

**Comment by ChaoKeeper** [comment]
It happened again today (a few minutes from this post).

**Comment by KiwiParis** [comment]
It happened to me yesterday (around 8.20pm NZDT -  New Zealand Daylight Time). My stats, name (name just ended up being my username KiwiParis) and race were changed from Bourgia to base human

**Comment by jvdoorn** [comment]
We think we found the issue, please wait till the next server restart (tomorrow 7am) and let me know if it persists after that.

**Comment by Enttauschung** [comment]
Enttauschung

Feb 1 2021 at around 6-7 pm

My name, race and stats were changed, leaving my race as human and my name as Enttauschung

**Comment by ChaoKeeper** [comment]
Believe it or not, it happened again yesterday at 4 PM EST

**Comment by KennyRD** [comment]
Keniio

Feb 1 2021 at around 6-7 pm

My name, race and stats were changed, leaving my race as human and my name is Keniio

**Comment by jvdoorn** [comment]
We have patched it this morning (changes took affect after the automatic restart). It is possible that it occurs one more time. If after that issues persist let me know.

**Comment by Jordankeeper** [comment]
Jordankeeper

5th Feb 2021 Around 10am Server time

Name, race, stats were all changed to base and human.

**Comment by Bl4nkShad0w** [comment]
Today I realized that my character settings were resetted again, this is the third time already. I don't really know the exact time it happened but I realized that it happened again, today.

**Comment by KennyRD** [comment]
Keniio

6th Feb 2021 Around  2:35 est

Name, race, stats were all changed to base and human.

**Comment by Sapphires-Rose** [comment]
Sapphires_Rose
7th of February, 8-9pm EST
Everything was reset

**Comment by jvdoorn** [comment]
We are quite confident that we fixed the bug. Please re-open this issue if you experience it again. Keep in mind that it is possible that your stats have to be set again one more time if it has not been set again yet.
