### ISSUE TITLE
Gravel bugged in default world edit

### ISSUE THREAD

**Issue by Bewby** [ThroneCraft/issues#145]
**Describe the bug**

When replacing gravel with another block in W/E, it always just deletes the gravel rather than replacing it. This is in default World Edit. It could just be a W/E bug that can't be fixed.

**Screenshots**
![gravel2](https://user-images.githubusercontent.com/74216336/106196127-ac51a880-6176-11eb-94ef-2a6e922f86de.PNG)

![gravel](https://user-images.githubusercontent.com/74216336/106195848-5b41b480-6176-11eb-8e50-2d82586bc82f.PNG)

![gravel3](https://user-images.githubusercontent.com/74216336/106196134-ae1b6c00-6176-11eb-9196-8ee6ee0066b2.PNG)

As you can see, the gravel should've turned to stone but it turned to nothing. It does the same no matter what block you replace it with.

***Minecraft username:***

Bewtiful

**Comment by Benlier** [comment]
Is this issue still ongoing?
