### ISSUE TITLE
Magic chest

### ISSUE THREAD

**Issue by Brsssh** [ThroneCraft/issues#147]
**Affected spells:**
Magic Chest
**Describe the bug**

There is no command to use the magic chest spell. I attempted /c magicchest, /c magicalchest, /c 'magic chest, and /c 'magical chest. In the /c menu its named as magical chest but when you click it nothing happens, and theres no autofill option when manually typing /c. I believe the spell worked until recently though I can't say for certain.

**Additional context**

The spell is supposed to open the user's enderchest when used

***Minecraft username:***

Brsssh

**Comment by FInnJp** [comment]
Sorry for late response. I do not know why it didnt work that time, however it seems to work now by doing /c magicchest

**Comment by Benlier** [comment]
Glad it has been resolved. Closing issue
