### ISSUE TITLE
Werewolf transformation deletes equipped armour.

### ISSUE THREAD

**Issue by TheDoverKing** [ThroneCraft/issues#149]
**Describe the bug**

When transforming into werewolf form with armour equipped the werewolf plugin seems to delete the armour permanently. 

**Screenshots**

Don't really have any. Just when you transform the armour items disapear.

**Additional context**

Pls fix I have lost two builder helmets now.

***Minecraft username:***

TheDoverKing

**Comment by FInnJp** [comment]
As a werewolf, you drop your armor (and whatever item you have at your hand) when you are under lvl 30. You sure it wasnt just a case of you dropping the items and forgetting to pick them up? (or couldnt pick them up due to full inventory)

**Comment by TheDoverKing** [comment]
Well I am over lvl 30 for a start and when I transform no items in my hand or inventory drop. The only thing that happens is any equipped armour seems to vanish and doesn't drop on the ground (like my poor builder helmets).

**Comment by FInnJp** [comment]
I see, then it is odd, as I cannot seem to be able to replicate what is happening to you. I'll try and check this with you when you'd be on, I'll so try and see others seem to be having the same problem.

**Comment by Benlier** [comment]
Unable to reproduce the issue
