### ISSUE TITLE
Forum broken??

### ISSUE THREAD

**Issue by meeshe9** [ThroneCraft/issues#150]
**Describe the issue**
Everytime I try to get my my forum account it says "403 FORBIDDEN". I was banned from the server over a year ago and I wanted to finally send in a ban app, but the website just won't let me in.
![Screenshot_20210526-233015](https://user-images.githubusercontent.com/84889440/119761830-89ac7380-be7a-11eb-9a16-a239e7efac71.png)

***Minecraft username:***

meeshe9

Discord user:
Broadway.bound (can't remeber the numbers, my discord is broken atm)

**Comment by jvdoorn** [comment]
This is not the place to report issues with the forum (not to mention that they are working for me). I suggest that you sent Remi or Finn a message on Discord if you can get that working.
