### ISSUE TITLE
The /ww command is broken

### ISSUE THREAD

**Issue by Zannythicca** [ThroneCraft/issues#151]
**Describe the bug**
When you type /ww it doesn't work 

**Screenshots**
https://gyazo.com/ee459254567a818cdd958d5bcadf41b0

**Additional context**

This occurred after the server restart on 6/20/21

***Minecraft username:***

zanithica

**Comment by FInnJp** [comment]
There seems to have been something that broke down from the recent Skinsrestorer update (a plugin that WW relies on). We need to wait until the devs of that plugin fix the issue, so for now we can only wait.

**Comment by FInnJp** [comment]
And I believe by now the problem should have fixed itself.
