### ISSUE TITLE
Flying MyPet spider

### ISSUE THREAD

**Issue by Bilbo821** [ThroneCraft/issues#16]
**Describe the bug**
Player with a spider pet was able to 'fly' with it through the air, like climbing walls but it seems to climb through the air blocks and fly essentially./ 

**Expected behaviour**
Spider not flying through the air

***Minecraft username:***
Bilbo821

**Comment by jvdoorn** [comment]
Could it be that you were experiencing lag?

**Comment by jvdoorn** [comment]
Until further information is provided this issue will be regarded as solved.
