### ISSUE TITLE
Hearts

### ISSUE THREAD

**Issue by Cake1100** [ThroneCraft/issues#17]
I have 5 extra hearts due to my race - Wood Elf - and it does not regenerate, despite using a potion.
![image](https://user-images.githubusercontent.com/70103074/90987909-8bad7300-e586-11ea-8d9a-ad077934c44e.png)

Username: Cakeeee

**Comment by Cake1100** [comment]
For some odd reason, it has finally decided to fix itself.

**Comment by jvdoorn** [comment]
I will be closing this issue then, please reopen if it persists.
