### ISSUE TITLE
Donation Crate Issue 

### ISSUE THREAD

**Issue by Soelaire** [ThroneCraft/issues#19]
I took a look at the donation chest given a few people mentioned it didn't give them items for some reasons, yet it does function fine other than that. I discovered an issue (please see the screenshots below) though the donation chest functions fine on my side (I got a dwarven boot armor piece), I am not completely sure if it is what causes the donation chest not to give a few players items. 

![2020-08-23_14 26 01_2](https://user-images.githubusercontent.com/70114241/90989209-cd6df780-e54d-11ea-90b9-09698207f6c7.png)
![2020-08-23_14 26 01](https://user-images.githubusercontent.com/70114241/90989225-e8406c00-e54d-11ea-9251-03436fb2c71b.png)
![2020-08-23_14 26 00](https://user-images.githubusercontent.com/70114241/90989230-ec6c8980-e54d-11ea-8bfb-733d600b268a.png)

~Soelaire

**Comment by jvdoorn** [comment]
In that case something is probably wrong in the Essential kits that are given by the Donation Crate. @MCVDK Could you test those?

**Comment by MCVDK** [comment]
This issue has supposedly been fixed by our wonderful Finn - the highlighted things are a visual issue. Finn will be looking more into that visual issue.
