### ISSUE TITLE
WorldEdit Glitches/Malfunction 

### ISSUE THREAD

**Issue by Azilerle** [ThroneCraft/issues#20]
Worldedit has been bugging and glitching. 
1. When I tried to copy and paste my build parts of it were missing. 
2. When I replaced to replace blocks it created a stone cube, and when I tried to //undo it didn't work wrecking my build. 
3. As said above, //undo doesn't work. 
4. Most of the WE commands are either working sometimes or not at all.

https://prnt.sc/u4ocux

***Minecraft username:***
Emperle__

**Comment by jvdoorn** [comment]
We've updated WorldEdit, please let us know if that fixed the issue.
