### ISSUE TITLE
My Tag Color

### ISSUE THREAD

**Issue by WoahItsFiish** [ThroneCraft/issues#21]
**Describe the bug**
A clear and concise description of what the bug is. When did you first experience this problem? And how to reproduce it?
In chat, local and global my tag is Dark Blue, for Anurk as it should be. However in tab my tag is Red for Khaz'mir which is wrong

**Expected behaviour**
My tag to be the correct color

**Screenshots**

![2020-08-24_19 41 55](https://user-images.githubusercontent.com/70179375/91106996-2d45ca80-e642-11ea-872a-aae421accbfc.png)

**Additional context**
N/A

***Minecraft username:***
Your Minecraft username.
WoahItsFiish

**Comment by MCVDK** [comment]
Issues with in game permissions - unneeded and overlapping roles conflicting with the TAB. This has been completed.
