### ISSUE TITLE
Bat Spawn Rate Through The Roof

### ISSUE THREAD

**Issue by WoahItsFiish** [ThroneCraft/issues#23]
**Describe the bug**
A clear and concise description of what the bug is. When did you first experience this problem? And how to reproduce it?
The bat spawn rate is so high. In Anurk there and hundreds of bats (not an exageration) usually there was only 5/6 in the entire place. now you have 15 bats on your screen at any given time.

**Expected behaviour**
Not to have a ton of bats?

**Screenshots**
![2020-08-24_19 48 19](https://user-images.githubusercontent.com/70179375/91179656-cf9e9600-e6b4-11ea-9a38-cde99d8c58c6.png)
![2020-08-24_19 59 52](https://user-images.githubusercontent.com/70179375/91179659-d0cfc300-e6b4-11ea-95a3-f81542bfa178.png)

**Additional context**
N/A

***Minecraft username:***
Your Minecraft username.
WoahItsFiish

**Comment by jvdoorn** [comment]
This issue should have been fixed, please reopen it if problems persist.
