### ISSUE TITLE
Werewolf Transformations

### ISSUE THREAD

**Issue by loulou71192** [ThroneCraft/issues#27]
Glitch where instead of transforming into a werewolf, changing my skin for other people as usual and giving me the powers and yada yada, the transformation and visual part is fluked. 

There's a delayed NPC standing slightly in front of me so it's blocking the view. Players cannot attack or use anything in front of them. Here are some screenshots:
![2020-08-24_22 41 38](https://user-images.githubusercontent.com/70107240/91351761-bc88e480-e7e0-11ea-9f3f-e73d8dab938c.png)
![2020-08-24_22 41 51](https://user-images.githubusercontent.com/70107240/91351762-bd217b00-e7e0-11ea-9db4-c865f2114679.png)
![2020-08-24_22 42 26](https://user-images.githubusercontent.com/70107240/91351764-bdba1180-e7e0-11ea-8b39-49e423564277.png)

**Comment by Benlier** [comment]
This looks like an issue with Lib's Disguises, which is a dependency of the werewolf plugin.

**Comment by Benlier** [comment]
Found a Fix! Hide your own disguise for yourself
/plugins/LibsDisguises/config.yml:133
`ViewSelfDisguises: false`

**Comment by Benlier** [comment]
Fixed in [https://github.com/ThroneCraft/server/commit/817bfa4cc207ba15325193eaa1160fafdf711e50](url)
