### ISSUE TITLE
Drinks plugin

### ISSUE THREAD

**Issue by loulou71192** [ThroneCraft/issues#29]
Have yet to try brewing anything, will update when I have but the colours on drinks have changed and are now random, including two of the same drink.

For example, I have Rose Wine, one of which is it's proper colour, one of which is green, another is orange, etc.

**Comment by FInnJp** [comment]
It seems like that is only an issue that happened with drinks which were carried over from 1.12.2 to 1.15.2 (so essentially when we changed server versions). All newly created drinks dont have the problem. From what I know, nothing else can be done other than replace the potions, but I believe just the color is what is broken, everything else about the drink should work as it used to.
