### ISSUE TITLE
Chat punctuation gone

### ISSUE THREAD

**Issue by Lumasauruwu** [ThroneCraft/issues#3]
**Description**
Punctuation for speech emotes and OOC no longer visible when put into the chat. When typing "x", * x *, and ((x, they are simply coloured, losing the "", **, and (( respectively.

**Expected Behaviour**
When typing "x", it should output "x" in the white colour, * x * fully in yellow, and ((x fully in grey.

***Minecraft username:***
Lumasaur

**Comment by jvdoorn** [comment]
Chat punctuation has partially been added back after a poll. It will take effect after the next restart.
