### ISSUE TITLE
Admin Command Disguise

### ISSUE THREAD

**Issue by Bilbo821** [ThroneCraft/issues#30]
**Describe the bug**
Admin's can't use the new disguise command but we could previously. 

**Expected behaviour**
Should allow us to disguise as other mobs/entities when using the command

**Screenshots**
https://prnt.sc/u7n6fz

**Additional context**
I spoke to Finn and we don't believe it's a matter of purchasing since GA's with the op permission are able to disguise, but rather admins having a lack of perms.

***Minecraft username:***
Bilbo821

**Comment by Benlier** [comment]
@Bilbo821 this plugin is working as intended. Only OPs can use disguises in the free version as stated on the [Lib's Disguises website](https://www.spigotmc.org/resources/libs-disguises-free.81/).
I don't believe the admin rank is supposed to get op, so they won't be able to disguise (sorry)
