### ISSUE TITLE
Can't Add Enchantment Books With Anvil

### ISSUE THREAD

**Issue by fbodeva** [ThroneCraft/issues#31]
**Describe the bug**
Using an anvil you are unable to add enchantment books to donation armor. 

**Expected behaviour**
You being able to add enchantment books to armor

***Minecraft username:***
Apoollo

**Comment by jvdoorn** [comment]
Are you unable to do so because of the enchantment cost? If so, that is default Minecraft behaviour.

**Comment by jvdoorn** [comment]
Alright we'll look into it.

**Comment by Benlier** [comment]
@fbodeva Could you tell me what type of armor you were trying to enchant, and what enchantment book you were using?
I've been unable to recreate this bug thus far

**Comment by Brsssh** [comment]
This is the error given, it does this with any boss or donor armor or weapons I've tested 
![Capture1111](https://user-images.githubusercontent.com/72952343/96628987-93fd0280-12d8-11eb-8ae3-4771a3ea256c.PNG)

**Comment by Brsssh** [comment]
Deleting the color code symbol from the name allows you to add the enchant, however I believe before the update this was done automatically for players without permission to create colored names
