### ISSUE TITLE
No Voting Key

### ISSUE THREAD

**Issue by Soelaire** [ThroneCraft/issues#32]
**Describe the bug:**
https://www.planetminecraft.com/server/thronecraft---medieval-roleplay-server/vote/
Players can't receive any voting keys from voting on this website even though they put their correct usernames and there is no message on the TC server saying "Thank you [insert username] for voting!". This issue hasn't been yet fixed since the 1.15 update. 

**Expected behaviour:**
The expected outcome is to obtain a single voting key after registering your username and clicking the Vote button, and see the message "Thank you [insert username] for voting!" on the TC server.

***Minecraft username:***
Soelaire

**Comment by jvdoorn** [comment]
Yes, we were having issues with the plugin handling rewards. We are looking into it.
