### ISSUE TITLE
Book clear commands still don't work.

### ISSUE THREAD

**Issue by KiwiParis** [ThroneCraft/issues#36]
This still doesn't work. I tried to commands you put before and it either says:
[This](https://gyazo.com/ca07484a64520da155f3f3c54fd2d2b1)
Or 
[This](https://gyazo.com/9a9f941d45486aae2bec4c5999f06cca)

_Originally posted by @KiwiParis in https://github.com/ThroneCraft/issues/issue_comments/708071943_

**Comment by Benlier** [comment]
The massivebooks plugin which offered this functionality has been removed [https://dev.bukkit.org/projects/massivebooks](url)
Add the plugin again, or find alternative?

**Comment by jvdoorn** [comment]
Massive books was not supported in 1.15 anymore. You can check if they support it now but I don't think so. 

We replaced most functionality with SimpleRename and Essentials. To me this appears to be a permission issue. 

See #24 for more details.
