### ISSUE TITLE
Book and Quills glitch

### ISSUE THREAD

**Issue by Brsssh** [ThroneCraft/issues#38]
**Describe the bug**
Occasionally, working within book and quills will cause the player's game to crash. I've noticed the issue most frequently when trying to flip through pages too quickly, but another person told me that it crashed them when they tried to write in a book. I'm not certain if this is a TC issue or a 1.15 issue but I've only really noticed it here. (Not that I use much other books on other 1.15 servers or worlds)

***Minecraft username:***
Brsssh

**Comment by jvdoorn** [comment]
This issue has been reported to Spigot and Minecraft. We will see what we can do. 

@Benlier I think updating Paper to the lates version might work.

**Comment by Benlier** [comment]
I believe this issue is completely client-side @jvdoorn 
I assume the full json of a book is send to a player. The rendering of that data is up to their client, so not much we can do.
We would need a crashlog

**Comment by jvdoorn** [comment]
@Brsssh could you provide us with a crash log? We'll then be able to determine if the cause is anything we can fix.

**Comment by jvdoorn** [comment]
[crash-2020-10-25_00.37.48-client.txt](https://github.com/ThroneCraft/issues/files/5439136/crash-2020-10-25_00.37.48-client.txt)

Indeed appears an issue with Minecraft/Spigot. We'll update our spigot version to see if that fixes it. If not that this out of our control.

**Comment by Brsssh** [comment]
It happened again, not sure if this is the same issue or another but I've got the crash report in case you want to compare
[crash-2020-11-07_23.34.50-client.txt](https://github.com/ThroneCraft/issues/files/5505880/crash-2020-11-07_23.34.50-client.txt)

**Comment by jvdoorn** [comment]
Appears to be the same error. Unfortunately that means that updating Paper did not work. I'm afraid that means that this issue is beyond our scope.
