### ISSUE TITLE
/lay bug

### ISSUE THREAD

**Issue by Brsssh** [ThroneCraft/issues#42]
**Describe the bug**

When /lay is used, if the user is wearing armor it shows them laying in their armor, as well as creating a sitting ghost of their armor above them.

**Screenshots**

![2020-10-19_16 24 25](https://user-images.githubusercontent.com/72952343/96513657-0e217e80-1228-11eb-867d-639b4399182d.png)
![2020-10-19_16 23 27](https://user-images.githubusercontent.com/72952343/96513660-0eba1500-1228-11eb-8b8c-8dd7a6645a4a.png)

***Minecraft username:***

Brsssh

**Comment by Benlier** [comment]
Do other players see the floating armor?

**Comment by Brsssh** [comment]
No. Only the person laying can see it
![2020-10-19_17 26 31](https://user-images.githubusercontent.com/72952343/96518409-77a58b00-1230-11eb-933d-7a44cc0f1e06.png)
https://media.discordapp.net/attachments/767876506046169098/767876925297000499/Screenshot_14.png?width=653&height=367

**Comment by Benlier** [comment]
Thank you for reporting this issue!
There is not much we can do about this. It also doesn't have a noticeable impact on RP and UX. I'll be contacting the creator of this plugin, and will follow up on this 😁

**Comment by Benlier** [comment]
I have been unable to make contact with the plugin author so do not have access to any source code or issue tracker
