### ISSUE TITLE
Second Layer Tab

### ISSUE THREAD

**Issue by ItsMegBaybee** [ThroneCraft/issues#43]
**Describe the bug**

So there seems to be a bug where if you are holding down tab to look at the list of players and someone is to teleport or use a warp boat, the second layer of their skin will appear on tab. For the second layer of someone's skin to appear on your tab they have to be relatively close to you for it to appear. I'm only guessing it happens when someone teleports or uses a warp boat because I couldn't seem to replicate it by holding it down while someone logged in.

**Screenshots**

If applicable, add screenshots to help explain your problem. Screenshots are generally helpful when the bug is related to visuals.

**Additional context**

***Minecraft username:***

ItsMegBaybee

**Comment by Brsssh** [comment]
I attempted to recreate this, at first I noticed I could in fact see the second layer of people I was nowhere near, I then relogged and had one of those people warp around a little bit but I couldn't see their second layer again until they came close to me

**Comment by Benlier** [comment]
Great work guys 👍 thanks for reporting with all these details! Definitely an odd bug with unexpected behaviour 🤔
I don't see this having an impact on anyone.

Again very well spotted, keep that up 👌
