### ISSUE TITLE
Being sent back to city selection

### ISSUE THREAD

**Issue by Brsssh** [ThroneCraft/issues#47]
**Describe the bug**

I need to gather specifics from people it effects, as at the moment it doesn't effect me, but it seems anyone from Volgrad or any outposts (possibly khazmir as well) are sent to the city selection when they die instead of their respective spawns
Next time I see it happen I'll try to record better who exactly it effects, though as far as I've seen it does not effect Fjoldrans for whatever reason

***Minecraft username:***

Brsssh

**Comment by jvdoorn** [comment]
Could you provide a list of where each group should spawn (where the spawn is a warp point).

**Comment by Sayyings** [comment]
Just for some input on this! It's just Volgrad people who are sent back to the city selection. Khaz'Mir and Fjoldr people are sent back to their city spawn point.

**Comment by jvdoorn** [comment]
Thank you for the input! We are aware of this. Some outpost groups are affected as well. We are waiting for a list of warps before fixing this issue.

**Comment by Brsssh** [comment]
Dorumirr (Dark green &2) /Warp Dorumirr (good warp)
Levstadt (Dark Blue &1) /Warp Levstadt (good warp)
Clocktower (purple &5) /Warp dragonhold (Teleports you to a hole underground)
Anurk (Light Blue &9) /warp Pollopoutpost (teleports you on top of the outpost)
Valseen (light green &a) /warp Raka_outpost (cant test)
Crucible (Dark red &4) /warp Crucible (teleports outside of the outpost, owner asked for the spawn to be inside of it)

I believe this is all of the independent outposts (Though there's a chance I'm mistaken), all other outposts should spawn at their respective cities
