### ISSUE TITLE
Syntactical Error in Rolling Commands

### ISSUE THREAD

**Issue by chernayas** [ThroneCraft/issues#50]
**Describe the bug**

When rolling in combat, a syntactical typo occurs where the thing being rolled and the word 'and' do not have a space between them.

**Screenshots**

https://gyazo.com/3eb0bac2d792214a5c11f0c3d449d82d

**Additional context**

N/A

***Minecraft username:***

Chernaya

**Comment by jvdoorn** [comment]
Duplicate of #49.
