### ISSUE TITLE
Book Bug #1

### ISSUE THREAD

**Issue by Brsssh** [ThroneCraft/issues#51]
**Describe the bug**

Despite fixes made yesterday, we are still unable to unlock or edit books made before the new plugin was implemented

**Screenshots**

![2020-10-22_12 15 36](https://user-images.githubusercontent.com/72952343/96919929-22f15280-1472-11eb-9776-65a4c3edf664.png)
![2020-10-22_12 15 26](https://user-images.githubusercontent.com/72952343/96919931-2389e900-1472-11eb-8914-b49038a65c4e.png)
![2020-10-22_12 15 33](https://user-images.githubusercontent.com/72952343/96919933-2389e900-1472-11eb-96e4-1b4ca08bcc6e.png)

***Minecraft username:***

Brsssh

**Comment by Benlier** [comment]
Probable cause: unlock command probably only checks author when it's copyrighted
Temporary fix: create a ticket, and ask staff to to unlock it for you. They should have bypass perms

**Comment by Brsssh** [comment]
Temporary fix does not work, staff members (mod and admin) are still unable to unlock the books
![5BB42095-E812-4C94-965A-F74406AB5319](https://user-images.githubusercontent.com/72952343/97219768-74fae680-1798-11eb-8ea4-9ab58d190794.png)
![EFC8785D-343A-426A-B53C-A973517675FC](https://user-images.githubusercontent.com/72952343/97219770-75937d00-1798-11eb-939f-516a42870423.png)
