### ISSUE TITLE
Issue with command prefixes.

### ISSUE THREAD

**Issue by TheAquaLord** [ThroneCraft/issues#56]
**Describe the bug**
Command /hungry which previously made you lose hunger no longer works and provides an error message.

**Screenshots**
![image](https://user-images.githubusercontent.com/67705452/97899288-01754e00-1d31-11eb-9503-156971cd0426.png)

**Additional context**
na

***Minecraft username:***
TheAquaLord

**Comment by jvdoorn** [comment]
These appear to be two separate issues. The prefix is already fixed in a test version of the plugin. The actual behaviour of `/hungry` will be looked at.

**Comment by TheAquaLord** [comment]
The screenshot was just to show the error that game up whilst trying to use /hungry , not necessarily for the prefix in general but getting that fixed would also be good.
