### ISSUE TITLE
Errors with tabs

### ISSUE THREAD

**Issue by Brsssh** [ThroneCraft/issues#58]
**Describe the bug**

There are 3 errors in the screenshot below, #1 the rank is empty, despite me being Builder, VIP and Jr Dev, #2 My name has no color despite how it should be either pink for builder or blue for Fjoldr, and #2 at the bottom it lists "Domain.com" as TC's official website

**Screenshots**

![2020-11-03_00 02 44](https://user-images.githubusercontent.com/72952343/97954261-a52e2080-1d68-11eb-9ab3-2dc45544ad14.png)

***Minecraft username:***

Brsssh

**Comment by Brsssh** [comment]
Oh, it also says the server name is "Server name"

**Comment by jvdoorn** [comment]
Where does it say this?

**Comment by Brsssh** [comment]
The first line of the Tab menu says "Server name"
The second line says Rank: No rank
My name has no color
then all the way at the bottom it says "Visit our webpage www.domain.com"

**Comment by Brsssh** [comment]
I also just realized tab isn't showing people's city colors at all. It shows their tag color. Travelers are Green, Wise are purple, people without tags are white

**Comment by jvdoorn** [comment]
Should be fixed, it is possible that this issue reoccurs after a restart, in that case please reopen this issue.
