### ISSUE TITLE
Ghosts

### ISSUE THREAD

**Issue by Brsssh** [ThroneCraft/issues#60]
**Describe the bug**

So, I happened to see this while I was investigating the messed up Levstadt warp, I went into GM 3 and saw what appeared to be a regular player also in GM 3. I dm'd them and asked what was going on and they said they had no idea what I was talking about, so I teleported to them and they were somewhere else entirely. For some reason a ghost of them is standing at the Levstadt warp.

**Screenshots**

![2020-11-03_22 55 36](https://user-images.githubusercontent.com/72952343/98071155-65c70900-1e28-11eb-8e74-74ced450b2f0.png)
![2020-11-03_22 55 46](https://user-images.githubusercontent.com/72952343/98071156-665f9f80-1e28-11eb-814d-457bcc809323.png)

**Additional context**

I can verify 100% that the person was not actually there, I have no idea why there ghost is there, I can only see their skin/username while in GM3

***Minecraft username:***

Brsssh

**Comment by jvdoorn** [comment]
Yeah it is a feature for Halloween 😛

Jokes aside, weird issue we'll have a look at it. Now that the server has restarted is the ghost gone at that location?

**Comment by Brsssh** [comment]
The ghost no longer appears to be there, I also tried showing it to a helper (Who also had access to gm3) and a builder (didn't have access to gm3) and neither could see it
![2020-11-03_22 55 46](https://user-images.githubusercontent.com/72952343/98158159-19b7ab00-1ea0-11eb-98bd-fc3430cb727a.png)

**Comment by Benlier** [comment]
- Unable to reproduce

- No impact on gameplay
