### ISSUE TITLE
Werewolf plugin addition

### ISSUE THREAD

**Issue by Brsssh** [ThroneCraft/issues#61]
**Is your feature request related to a problem? Please describe.**
Yes and no. Witherfangs are currently one of the lesser played werewolf clans, because of this every time a witherfang alpha dies (IC or OOC) the alpha reverts to the player with the most points or whatever the standard is. The player who it reverts to every single time has been perma banned for more rule violations than I can even remember, including but not limited to multiple counts of hacking and using alts to avoid bans. This can't be changed however, because staff are unable to take away his points, or swap him to human mode while he's offline. Meaning no matter what with the current system, every time a witherfang alpha dies the next alpha is set to a permabanned player until staff can manually change it.

**Describe the solution you'd like**
Create some wat to remove player's werewolfism or their points without them being online

***Minecraft username:***
Brsssh

**Comment by Benlier** [comment]
Server-specific issue that requires an Operator
