### ISSUE TITLE
Armor stand plugin

### ISSUE THREAD

**Issue by Brsssh** [ThroneCraft/issues#67]
**Is your feature request related to a problem? Please describe.**

https://thronecraft-server.enjin.com/mobile/forum/viewthread/m/13784224/id/33002557-plugin-suggestion-armor-stand

**Describe the solution you'd like**
Find some way to implement this plugin, or possibly create a new version of it.

**Additional context**
While the plugin was never officially marked as accepted, Finn attempted to add it a little while after but was unable to, I believe due to problems with other plugins. I’m not sure of the specific issues and doubt he would remember them as it was so long ago. The plugin appears to be updated up to 1.16 so hopefully it won’t be too hard to get it implemented

***Minecraft username:***
Brsssh

**Comment by Benlier** [comment]
> Finn attempted to add it a little while after

@FInnJp can you confirm?

**Comment by Benlier** [comment]
@Brsssh Do you see this as something to be used by builders, or all players?

**Comment by Brsssh** [comment]
I think it would be nice if all players had access to it. Like I said on the forum post it doesn’t cause lag (as I once put hundreds in one small room with no issues) so it shouldn’t cause problems for everyone to have access and might be nice to be able to add some cool immersion

**Comment by Benlier** [comment]
Plugin test notes:

- Works on 1.15.2

- Plug and play

- Works with WE if using -e param **Hard to repair if forgotten** this is default behaviour though

- Hard to find invisible empty armorstands > proposing shorthand for `/effect give @e[distance=0..10, type=minecraft:armor_stand] minecraft:glowing 4`

- Players can steal from armorstands, traceable with /co lookup radius:5

- **Players can steal by accessing the equipment with the editor tool. This is untraceable**

Definitely need to find a fix for untraceable stealing before proceeding

**Comment by Benlier** [comment]
I created an issue in the plugin's issue tracker https://github.com/RypoFalem/ArmorStandEditor/issues/37

**Comment by Benlier** [comment]
Fixed RypoFalem/ArmorStandEditor#37 in https://github.com/Benlier/ArmorStandEditor/tree/feature/equipmentPerm
