### ISSUE TITLE
All placed Locked Doors and Keyrings have broken

### ISSUE THREAD

**Issue by Zannythica** [ThroneCraft/issues#8]
**Describe the bug**
All placed Locked Doors and Keyrings have broken, meaning that the locked doors are normal doors and you cannot access the keys in your inventory from the key ring. I presume anything placed that was locked has this issue.

**Comment by MCVDK** [comment]
Not relevant; was related to old plugin - however Zani has noted a need for a method to unlock a door again.

**Comment by jvdoorn** [comment]
As far as I can tell unlocking a door works just fine using `/unlock` as long as you have the key.

**Comment by MCVDK** [comment]
Yep. It does - doesn't work for admins alone though. Refer to issue #13

**Comment by jvdoorn** [comment]
This issue can be closed then @MCVDK ?

**Comment by jvdoorn** [comment]
This issue will be closed in favour of #14
